version: '3'

services:
  frontend:
    build: frontend
    volumes:
      - frontend-dist:/frontend/dist:ro

  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - backend-static:/backend/static

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
    links:
      - "backend:backend"
      - "frontend:frontend"
    volumes:
      - backend-static:/app/static
      - frontend-dist:/app/static/js

volumes:
  frontend-dist:
  backend-static: